### ISSUE TITLE
Love this

### ISSUE THREAD

**Issue by samselikoff** [jayphelps/ember-model-batch#1]
This is a really good idea. Did you have success with it? Run into issues? Now that json:api has an [official bulk extension](http://jsonapi.org/extensions/bulk/) it would be great reanimate this lib, make it an addon and play around with the api.

**Comment by jayphelps** [comment]
@samselikoff It worked exactly as advertised for me when I was at Pivotshare. It's likely still in use there, but I don't maintain any project that requires it anymore. Briefly looking over the code, it actually should still work in today's ember-data since it only uses the `ajax` method which isn't a private API and still exists today.

I don't have time to update this to support the json:api bulk extension, but happy to merge PRs. Given the nature of OS and the MIT license, you can also certainly just copy-pasta this code and make your own as well. I give you expressly granted permission to exclude me from credit as well, as long as you retain the MIT license. The code isn't very complex, just dotting all the i's in case you were curious. STEAL MY CODE PLZ :+1:

**Comment by samselikoff** [comment]
Sweet, thanks man. Would love to get this to a point where we can kick the tires with json:api batch.

Great work, it's a fantastic idea.
